# .travis.yml
language: node_js
node_js:
  - 0.8
before_script:
  - mysql -e "CREATE DATABASE $DB_NAME;"
  - tar -zxvf seed.sql.tgz
  - mysql $DB_NAME < seed.sql
services:
  - redis-server
env:
  - SERVER_HOST='127.0.0.1' DB_NAME="goldstone"
branches:
  only:
    - master
    - develop
    - /^deploy-.*$/
notifications:
  webhooks:
    urls:
      on_failure:never
      - http://42.121.104.247:2002/deploy
