#!/bin/bash

NodeEnv="$(./env.js)"
export NODE_ENV=$NodeEnv

AppName=gs-interface-$NodeEnv.js
#pkill -9 -f $AppName
forever stop $AppName

cp app.js $AppName
mkdir -p log
#mv log/app.log log/app`date +%Y%m%d%H%M%S`.log
#mv log/out.log log/old.log
#mv log/err.log log/oldErr.log
mv log/forever.log log/oldForever.log
forever start -l `pwd`/log/forever.log $AppName
#forever start -l `pwd`/log/forever.log -o log/out.log -e log/err.log $AppName
#node $AppName > log/app.log 2>&1 &
sleep 3
netstat -ntl
